def getSkillInfo(name):
    skillType = ""
    calc = ""
    cooldown = ""
    info = ""


    if name == 'Abyss Nova': skillType = 'Buff'; cooldown = '2 Turns'; calc = 'T.ATK+MAG T.MAG+MAG T.RES-MAG'; info = 'This is the power of Lord Yatagarasu, the Black Sun!'
    if name == 'Acid': skillType = 'Party Debuff'; cooldown = '2 Turns'; calc = 'T.DEF-ATK'; info = ''
    if name == 'Archaeological Punch': skillType = 'Attack'; cooldown = '3 Turns'; calc = '(ATK+SKL*2)-T.DEF'; info = 'A punch filled with the power of archaeology. Wait, what?'
    if name == 'Astonish': skillType = 'Basic Attack'; cooldown = '0 Turns'; calc = 'ATK*2-T.DEF'; info = ''
    if name == 'Bide': skillType = 'Buff'; cooldown = '2 Turns'; calc = 'T.DEF+VIT*0.5'; info = ''
    if name == 'Bite': skillType = 'Attack'; cooldown = '2 Turns'; calc = 'ATK*2-T.DEF (SKL*2)'; info = ''
    if name == 'Blazing Dragon': skillType = 'Attack'; cooldown = '3 Turns'; calc = 'ATK*3-T.DEF (SKL*2)'; info = 'Shoryuken!'
    if name == 'Blazing Star': skillType = 'Buff'; cooldown = '2 Turns'; calc = 'T.SPD+MAG'; info = 'Also why are all of her spell cards so awesome? Like all of them?'
    if name == 'Blazing Wheel': skillType = 'Buff'; cooldown = '2 Turns'; calc = 'T.SPD+SPD T.SKL+SPD T.DEF-SPD'; info = 'I\'m not sure what\'s going on, but it looks impressive.'
    if name == 'Broom Bash': skillType = 'Basic Attack'; cooldown = '0 Turns'; calc = 'ATK*2-T.DEF'; info = ''
    if name == 'Calculated Strike': skillType = 'Attack'; cooldown = '2 Turns'; calc = 'ATK*2-T.DEF (SKL*2)'; info = ''
    if name == 'Cat\'s Walk': skillType = 'Team Attack'; cooldown = '4 Turns'; calc = 'ATK*2-T.DEF (SPD*3)'; info = 'She\'s a lot faster in her cat form.'
    if name == 'Chakram': skillType = 'Basic Attack'; cooldown = '0 Turns'; calc = 'ATK*2-T.DEF'; info = 'Slicing weapons. Don\'t throw them though, that\'s illegal.'
    if name == 'Chess Match': skillType = 'Attack'; cooldown = '5 Turns'; calc = 'SKL*3-SKL'; info = 'A gentleman\'s game. How does it cause damage though?'
    if name == 'Chop': skillType = 'Basic Attack'; cooldown = '0 Turns'; calc = 'ATK*2-T.DEF'; info = ''
    if name == 'Cleave': skillType = 'Team Attack'; cooldown = '1 Turns'; calc = 'ATK*2-T.DEF '; info = ''
    if name == 'Control Rod Crush': skillType = 'Basic Attack'; cooldown = '0 Turns'; calc = 'ATK*2-T.DEF'; info = 'Is it a punch or a kick? It\'s her third leg after all.'
    if name == 'Counter': skillType = 'Buff'; cooldown = '0 Turns'; calc = 'T.DEF+VIT*0.2 T.ATK+VIT*0.2'; info = ''
    if name == 'Crescent Rose': skillType = 'Basic Attack'; cooldown = '0 Turns'; calc = 'ATK*2-T.DEF'; info = 'It\'s a High-Caliber Sniper-Scythe.'
    if name == 'Critical Thinking': skillType = 'Buff'; cooldown = '2 Turns'; calc = 'T.SKL+SKL'; info = 'An important skill to master.'
    if name == 'Crowbar': skillType = 'Basic Attack'; cooldown = '0 Turns'; calc = 'ATK*2-T.DEF'; info = 'Quite effective. Don\'t underestimate a crowbar.'
    if name == 'Cup of Tea': skillType = 'Heal'; cooldown = '2 Turns'; calc = 'T.HP+SKL'; info = 'A good cup of tea will fix you right up.'
    if name == 'Curse': skillType = 'Debuff'; cooldown = '1 Turns'; calc = 'T.LUK-MAG*1.5'; info = 'Misforture follows those on the wrong side of a curse god.'
    if name == 'Divine Intervention': skillType = 'Party Buff'; cooldown = '3 Turns'; calc = 'T.LUK+(MAG+LUK)*0.5'; info = 'How did you dodge that? It must of been a miracle or something.'
    if name == 'Double-Edge': skillType = 'Attack'; cooldown = '2 Turns'; calc = 'ATK*3-T.DEF'; info = ''
    if name == 'Earth Spike': skillType = 'Attack'; cooldown = '3 Turns'; calc = 'MAG*4-T.DEF'; info = 'Make a mountain out of... well nothing really.'
    if name == 'Every puzzle has an answer!': skillType = 'Debuff'; cooldown = '2 Turns'; calc = 'T.DEF-SKL'; info = 'He\'s good at that. You know, solving puzzles.'
    if name == 'Exteeeending Aaaaarm': skillType = 'Party Attack'; cooldown = '3 Turns'; calc = 'ATK*2-T.DEF'; info = 'Mechanical hands are cool but also terrifying.'
    if name == 'Fae Round': skillType = 'Party Attack'; cooldown = '1 Turns'; calc = 'MAG*2-T.RES'; info = 'Well, it\'s an orb... and it\'s green... and... it\'s the wave element... thingy.'
    if name == 'Falling Star': skillType = 'Attack'; cooldown = '5 Turns'; calc = '(MAG+LUK*3)-T.RES'; info = 'Terraria wants it\'s Fallen Stars back. I don\'t think she going to give them up though.'
    if name == 'Fencing': skillType = 'Basic Attack'; cooldown = '0 Turns'; calc = 'ATK*2-T.DEF'; info = 'A hobby fit for a gentleman.'
    if name == 'Fimbulvetr': skillType = 'Party Attack'; cooldown = '5 Turns'; calc = '(ATK+DEF+RES)-T.DEF'; info = 'Your enemies will feel the icy bitterness winter can bring.'
    if name == 'Final Spark': skillType = 'Attack'; cooldown = '10 Turns'; calc = 'MAG*10-T.RES*2'; info = 'A bigger laser of course! But it\'s name makes it sound like it should be used last.'
    if name == 'Flickering Stars': skillType = 'Attack'; cooldown = '6 Turns'; calc = '(MAG+SPD*2)-T.RES (SPD*2)'; info = 'An attack so fast, time seems to cease.'
    if name == 'Fury Swipes': skillType = 'Attack'; cooldown = '2 Turns'; calc = 'ATK-T.DEF (SPD*4)'; info = ''
    if name == 'Geyser Column': skillType = 'Attack'; cooldown = '4 Turns'; calc = 'MAG*7-T.RES*2'; info = 'Ow ow ow! That\'s hot!'
    if name == 'Geyser': skillType = 'Attack'; cooldown = '1 Turns'; calc = 'MAG*3-T.RES'; info = 'Where\'d all that water come from? Does it matter?'
    if name == 'Gohei Smack': skillType = 'Basic Attack'; cooldown = '0 Turns'; calc = 'ATK*2-T.DEF'; info = 'You could always try just smacking them. That should do something at least?'
    if name == 'Guard': skillType = 'Buff'; cooldown = '3 Turns'; calc = 'T.DEF+DEF*2'; info = 'Carefully shielding himself or those around him, He refuses to fall.'
    if name == 'Haze': skillType = 'Team Debuff'; cooldown = '2 Turns'; calc = 'T.SKL-MAG*0.5'; info = ''
    if name == 'Headbutt': skillType = 'Basic Attack'; cooldown = '0 Turns'; calc = 'ATK*2-T.DEF'; info = ''
    if name == 'Heal': skillType = 'Heal'; cooldown = '1 Turns'; calc = 'T.HP+MAG'; info = 'A simple healing skill.'
    if name == 'Hell\'s Tokamak': skillType = 'Attack'; cooldown = '2 Turns'; calc = 'MAG*2'; info = 'A power so incredible no defence can protect you. Better get out of the way!'
    if name == 'High-Speed Rush': skillType = 'Attack'; cooldown = '3 Turns'; calc = 'ATK*2-T.DEF (SPD*3)'; info = 'Brought to you by Gravity Dust!'
    if name == 'Howl': skillType = 'Debuff'; cooldown = '2 Turns'; calc = 'T.DEF-ATK'; info = ''
    if name == 'Idle': skillType = 'Basic Attack'; cooldown = '0 Turns'; calc = 'ATK*2-T.DEF'; info = 'He\'s not doing anything. Maybe he\'s asleep?'
    if name == 'Iron Rings': skillType = 'Basic Attack'; cooldown = '0 Turns'; calc = 'ATK*2-T.DEF'; info = 'Throw rings at things! They are rather sharp.'
    if name == 'Janken Paper!': skillType = 'Attack'; cooldown = '2 Turns'; calc = 'ATK*2-T.DEF (SKL*2)'; info = 'Get wooshed.'
    if name == 'Janken Rock!': skillType = 'Attack'; cooldown = '2 Turns'; calc = 'ATK*3-T.DEF'; info = 'Good old rock.'
    if name == 'Janken Scissors!': skillType = 'Attack'; cooldown = '2 Turns'; calc = 'ATK*2-T.DEF (SPD*2)'; info = 'This is basically a sword attack right?'
    if name == 'Kasha\'s Claws': skillType = 'Basic Attack'; cooldown = '0 Turns'; calc = 'ATK*2-T.DEF'; info = 'It\'s said that Kasha steal the corpses of sinners.'
    if name == 'Let\'s Snuggle Forever': skillType = 'Party Attack'; cooldown = '5 Turns'; calc = 'ATK*4-T.DEF'; info = ''
    if name == 'Lunge': skillType = 'Basic Attack'; cooldown = '0 Turns'; calc = 'ATK*2-T.DEF'; info = ''
    if name == 'Magic Missile': skillType = 'Attack'; cooldown = '1 Turns'; calc = 'MAG*2-T.RES*0.5'; info = 'Actually looks like a missile, unlike in a certain Role-playing Game.'
    if name == 'Master Spark': skillType = 'Attack'; cooldown = '4 Turns'; calc = 'MAG*5-T.RES'; info = 'A giant laser. What more could you want?'
    if name == 'Maul': skillType = 'Attack'; cooldown = '2 Turns'; calc = 'ATK*3-T.DEF'; info = ''
    if name == 'Miracle': skillType = 'Buff'; cooldown = '1 Turns'; calc = 'T.LUK+MAG*1.5'; info = ''
    if name == 'Mirror Coat': skillType = 'Buff'; cooldown = '0 Turns'; calc = 'T.MAG+VIT*0.2 T.RES+VIT*0.2'; info = ''
    if name == 'Needle Mountain of a Former Hell': skillType = 'Team Attack'; cooldown = '2 Turns'; calc = 'MAG*3-T.RES'; info = 'This one is rather spiky. Like that\'s mostly what it is. Spikes.'
    if name == 'Night Shade': skillType = 'Attack'; cooldown = '3 Turns'; calc = 'MAG*2-T.RES'; info = ''
    if name == 'Non-Directional Laser': skillType = 'Team Attack'; cooldown = '2 Turns'; calc = 'MAG*2-T.RES'; info = 'A half-borrowed spell. Makes you wonder how many of her spells aren\'t a blatant copy?'
    if name == 'Omikuji Barrage': skillType = 'Team Attack'; cooldown = '4 Turns'; calc = 'MAG*2-T.LUK'; info = 'You\'re getting a fortune whether you like it or not.'
    if name == 'Optical Camouflage': skillType = 'Buff'; cooldown = '2 Turns'; calc = 'T.LUK+SKL'; info = 'You can\'t hit what you can\'t see...'
    if name == 'Overhead Chop': skillType = 'Attack'; cooldown = '1 Turns'; calc = 'ATK*4-T.DEF'; info = ''
    if name == 'Pep Talk': skillType = 'Buff'; cooldown = '2 Turns'; calc = 'T.SKL+ATK T.SPD+ATK T.DEF-ATK'; info = ''
    if name == 'Photon Torpedo': skillType = 'Attack'; cooldown = '2 Turns'; calc = 'ATK*3-T.RES'; info = 'How is it a torpedo when it\'s not used in water?'
    if name == 'Piercing Howl': skillType = 'Team Attack'; cooldown = '1 Turn'; calc = 'MAG*2-T.RES'; info = ''
    if name == 'Play Rough': skillType = 'Basic Attack'; cooldown = '0 Turns'; calc = 'ATK*2-T.DEF'; info = ''
    if name == 'Poison Sting': skillType = 'Attack'; cooldown = '2 Turns'; calc = 'ATK*2-T.DEF*0.5 (SPD*2)'; info = ''
    if name == 'Pound': skillType = 'Basic Attack'; cooldown = '0 Turns'; calc = 'ATK*2-T.DEF'; info = ''
    if name == 'Propel': skillType = 'Buff'; cooldown = '3 Turns'; calc = 'T.SPD+SPD*2'; info = '*Helicopter noises*'
    if name == 'Punch': skillType = 'Basic Attack'; cooldown = '0 Turns'; calc = 'ATK*2-T.DEF'; info = 'A basic attack.'
    if name == 'Quick Attack': skillType = 'Attack'; cooldown = '1 Turns'; calc = 'ATK*2-T.DEF (SPD*2)'; info = ''
    if name == 'Razor Leaf': skillType = 'Attack'; cooldown = '3 Turns'; calc = 'ATK*2-T.DEF (SKL*2)'; info = ''
    if name == 'Rekindling of Dead Ashes': skillType = 'Heal'; cooldown = '2 Turns'; calc = 'T.HP+MAG (IF T.HP=0 THEN MAG*2)'; info = 'A healing spell that works better on dead people.'
    if name == 'Repair': skillType = 'Heal'; cooldown = '3 Turns'; calc = 'T.HP+SKL T.ATK+SKL'; info = 'You can ask her to repair something, just expect a few modifications.'
    if name == 'Rock Fling': skillType = 'Team Attack'; cooldown = '5 Turns'; calc = 'MAG*3-T.DEF'; info = 'If it works, it works. Rocks hurt.'
    if name == 'Rocket Dive': skillType = 'Team Attack'; cooldown = '1 Turn'; calc = 'ATK*1.5-T.DEF'; info = 'Where\'d she go? OH NO SHE\'S COMING BACK'
    if name == 'Round 2!': skillType = 'Buff'; cooldown = '3 Turns'; calc = 'T.SPD+VIT'; info = 'Again!'
    if name == 'Salute': skillType = 'Basic Attack'; cooldown = '0 Turns'; calc = 'ATK*2-T.DEF'; info = ''
    if name == 'Savage': skillType = 'Attack'; cooldown = '3 Turns'; calc = 'ATK*4-T.DEF'; info = ''
    if name == 'Scratch': skillType = 'Basic Attack'; cooldown = '0 Turns'; calc = 'ATK*2-T.DEF'; info = ''
    if name == 'Shadow Ball': skillType = 'Attack'; cooldown = '0 Turns'; calc = 'MAG*2-T.RES*0.5'; info = ''
    if name == 'Shadow Claw': skillType = 'Attack'; cooldown = '1 Turns'; calc = 'ATK*2-T.DEF (SKL*3)'; info = ''
    if name == 'Shadow Tag': skillType = 'Party Debuff'; cooldown = '5 Turns'; calc = 'T.SPD-VIT*0.5 T.LUK-VIT*0.5'; info = ''
    if name == 'Shield Bash': skillType = 'Attack'; cooldown = '3 Turns'; calc = 'DEF+ATK*2-T.DEF'; info = ''
    if name == 'Shoot': skillType = 'Attack'; cooldown = '2 Turns'; calc = 'ATK*2-T.DEF (SKL*2)'; info = ''
    if name == 'Show Me Rock!': skillType = 'Buff'; cooldown = '1 Turns'; calc = 'T.ATK+VIT'; info = 'Get ready...'
    if name == 'Slash': skillType = 'Basic Attack'; cooldown = '0 Turns'; calc = 'ATK*2-T.DEF'; info = ''
    if name == 'Sleep Powder': skillType = 'Debuff'; cooldown = '1 Turns'; calc = 'T.SKL-ATK T.LUK-ATK'; info = ''
    if name == 'Sludge': skillType = 'Team Attack'; cooldown = '2 Turns'; calc = 'MAG*2-T.RES'; info = ''
    if name == 'Smog': skillType = 'Team Attack'; cooldown = '2 Turns'; calc = 'MAG*3-T.RES (SKL*0.5)'; info = ''
    if name == 'Smokescreen': skillType = 'Team Debuff'; cooldown = '2 Turns'; calc = 'T.SKL-MAG*0.5'; info = ''
    if name == 'Speed': skillType = 'Buff'; cooldown = '2 Turns'; calc = 'T.SPD+SPD'; info = '"I\'m not slow, see? You don\'t have to worry about me!"'
    if name == 'Subterranean Sun': skillType = 'Team Attack'; cooldown = '4 Turns'; calc = 'MAG*3-T.RES (T.LUK*0.5)'; info = 'It\'s a sun so it has it\'s own gravity. Enemies will have a tough time trying not to get pulled in.'
    if name == 'Super Scope 3D': skillType = 'Attack'; cooldown = '6 Turns'; calc = 'ATK*4-T.DEF*0.5'; info = 'Boom. Headshot. Maybe.'
    if name == 'Supersonic': skillType = 'Debuff'; cooldown = '2 Turns'; calc = 'T.ATK-ATK'; info = ''
    if name == 'Swords Dance': skillType = 'Buff'; cooldown = '1 Turns'; calc = 'T.ATK+ATK*2'; info = ''
    if name == 'Tackle': skillType = 'Basic Attack'; cooldown = '0 Turns'; calc = 'ATK*2-T.DEF'; info = ''
    if name == 'Tear': skillType = 'Basic Attack'; cooldown = '0 Turns'; calc = 'ATK*2-T.DEF'; info = ''
    if name == 'Threaten': skillType = 'Buff'; cooldown = '2 Turns'; calc = 'T.SKL+ATK T.SPD+ATK T.DEF-ATK'; info = ''
    if name == 'Vengeful Cannibal Spirit': skillType = 'Attack'; cooldown = '1 Turns'; calc = 'ATK+MAG-T.DEF*0.5'; info = 'I don\'t know why but this attack gives me the creeps.'
    if name == 'Vine Whip': skillType = 'Basic Attack'; cooldown = '0 Turns'; calc = 'ATK*2-T.DEF'; info = ''
    if name == 'Watch Out': skillType = 'Buff'; cooldown = '2 Turns'; calc = 'T.LUK+ATK'; info = ''
    if name == 'Will-O-Wisp': skillType = 'Debuff'; cooldown = '2 Turns'; calc = 'T.ATK-MAG'; info = ''
    if name == 'Windstorm': skillType = 'Party Attack'; cooldown = '5 Turns'; calc = '(MAG+LUK*2)-T.RES'; info = 'Just try to not get blown away.'
    if name == 'Wood Hammer': skillType = 'Attack'; cooldown = '2 Turns'; calc = 'ATK*4-T.DEF'; info = ''
    if name == 'Wrap': skillType = 'Debuff'; cooldown = '3 Turns'; calc = 'T.SPD-ATK'; info = ''
    if name == 'Yatagarasu Dive': skillType = 'Attack'; cooldown = '2 Turns'; calc = 'ATK*2-T.DEF (SKL*3)'; info = 'Uses the power of Yatagarasu to make a more accurate attack. Utsuho\'s always been more of the blast everything type.'


    output = f"\n    -{name}-\n\nType:\n    {skillType}\nCooldown:\n    {cooldown}\nCalculations:\n    {calc}\nDescription:\n    {info}"
    return output